"""Two-probe mode 5: propagation velocities from staggered probe insertions.

``mipt_probed.exe 2 N reals circ 5 p s_max r_max delta_max`` Bell-entangles
ancilla ``A`` with a random site ``x0`` after equilibration, waits ``Delta``
timesteps, Bell-entangles ancilla ``B`` with ``x0 + r``, and then records
``rho_AB`` for every elapsed ``s``. Both ancillas sit outside the circuit, so a
system-only unitary acts as the identity on ``rho_AB`` and cannot correlate them
at all: every ``A``--``B`` correlation seen here is generated by the intervening
measurement record.

Why this and not the one-probe front
------------------------------------
The one-probe protocol (:mod:`data_analysis.front`) watches a single injected
ebit spread into receiver blocks of fixed width. Its classical channel is easy to
follow, but its negativity vanishes *exactly* a few sites out -- the reference's
one ebit delocalizes and a microscopic receiver's marginal becomes PPT -- so the
entanglement front has a range rather than a velocity. Two isolated qubit
ancillas do not have that problem: ``rho_AB`` is 2x2 by 2x2, where ``N = 0``
unambiguously means separable, and the correlation being measured is created
rather than diluted.

The price is that ``s_arr`` here confounds two propagation legs, so a naive
velocity would carry a factor-of-two ambiguity. The staggered insertion removes
it. If the two influence regions travel at ``v_mu`` and meet, the arrival time
after the second insertion behaves as

    s_arr(r, Delta) = b + c * max(lambda_mu * r - Delta, 0),

with ``c = 1/2`` for a meet-in-the-middle mechanism and ``c = 1`` for a one-way
crossing -- but *either way* the kink sits at

    Delta_c(r) = b' + lambda_mu * r,

so the slope of the breakpoint against separation is the one-way ``lambda_mu``
regardless of which mechanism is at work. That is what this module fits, and it
is the reason the delay axis is scanned at all.

The last panel then reports ``Delta_{N,c}(r) - Delta_{J,c}(r)``, which separates
the three hypotheses directly: growing linearly means genuinely different
velocities, constant means one velocity plus a fixed entanglement-formation
delay, and sublinear growth means the gap is a detectability effect of the
threshold rather than a front.

Two things to know before reading a number off this
---------------------------------------------------
``J`` is the Henderson--Vedral classical correlation, maximized over every
projective measurement of ``A``, and ``D = I - J`` is the quantum discord --
*not* entanglement. A discord front says quantum correlation arrived, which is a
weaker claim than the negativity front makes.

Arrival times oscillate with the parity of ``Delta``. One timestep is one
brickwork layer, so consecutive delays insert ``B`` into layers of opposite bond
parity and the first layer acting on ``B``'s partner site couples it in
different directions. The oscillation is real, not noise, and it enters
``Delta_c`` as extra scatter rather than as a bias so long as the fit window
holds both parities. ``delta_parity`` fits one parity at a time when that needs
checking.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping, Sequence
import warnings

import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import numpy as np
import pandas as pd

from .fitting import _weighted_linear_fit
from .front import _CLASSICAL_COLOR, _QUANTUM_COLOR, _arrival_times, LOG2
from .loading import _find_column, _resolve_files, resolve_metadata
from .plotting import _annotate_axes, _mi_unit_spec, _show

# Every two-probe mode-5 observable, with the largest value it can take.
#
# Unlike the one-probe protocol there is no "injected amplitude" to normalize
# against -- at s=0 the two ancillas are uncorrelated and every metric is zero by
# construction. ``ceiling`` is therefore the theoretical maximum of the quantity
# on a two-qubit state. It is only a fallback reference for thresholds: the
# channels saturate at very different fractions of their ceilings (10% for J
# against 4% for the negativity at L=16, p=0.16), so a shared q against the
# ceiling is not a shared q against the signal. The default reference is the
# observed peak -- see _threshold_level.
_STAGGER_METRICS: dict[str, dict[str, Any]] = {
    "I": {
        "mean": ("I_mean",), "stderr": ("I_stderr",),
        "label": r"$I(A{:}B)$", "ceiling": 2.0 * LOG2, "entropy_like": True,
        "kind": "total",
    },
    "J": {
        "mean": ("J_mean",), "stderr": ("J_stderr",),
        "label": r"$J(A{\to}B)$", "ceiling": LOG2, "entropy_like": True,
        "kind": "classical",
    },
    "discord": {
        "mean": ("discord_mean",), "stderr": ("discord_stderr",),
        "label": r"$D=I-J$", "ceiling": LOG2, "entropy_like": True,
        "kind": "quantum",
    },
    "C_Z": {
        "mean": ("C_Z_mean",), "stderr": ("C_Z_stderr",),
        "label": r"$C_Z$", "ceiling": LOG2, "entropy_like": True, "kind": "classical",
    },
    "C_max": {
        "mean": ("C_max_mean",), "stderr": ("C_max_stderr",),
        "label": r"$C_{\max}$", "ceiling": LOG2, "entropy_like": True,
        "kind": "classical",
    },
    "negativity": {
        "mean": ("negativity_mean",), "stderr": ("negativity_stderr",),
        "label": r"$\mathcal{N}$", "ceiling": 0.5, "entropy_like": False,
        "kind": "quantum",
    },
    "log_negativity": {
        "mean": ("log_negativity_mean",), "stderr": ("log_negativity_stderr",),
        "label": r"$E_{\mathcal{N}}$", "ceiling": LOG2, "entropy_like": True,
        "kind": "quantum",
    },
    "coherent_information": {
        "mean": ("coherent_information_mean",), "stderr": ("coherent_information_stderr",),
        "label": r"$I_c(A\rangle B)$", "ceiling": LOG2, "entropy_like": True,
        "kind": "quantum",
    },
    # Conditioned on there being any entanglement at all, so it separates "the
    # entanglement got weaker" from "it got rarer". Undefined wherever no
    # trajectory was positive, and NaN there rather than zero.
    "conditional_negativity": {
        "mean": ("conditional_negativity_mean",), "stderr": ("conditional_negativity_stderr",),
        "label": r"$\mathbb{E}[\mathcal{N}\,|\,\mathcal{N}>0]$", "ceiling": 0.5,
        "entropy_like": False, "kind": "quantum",
    },
    # Fires as soon as one trajectory has any entanglement, so it is far more
    # sensitive than the mean -- and, for the same reason, is not a safe front
    # detector: the positivity test runs at 1e-12 while an fp32 state vector
    # produces round-off negativities well above that.
    "positive_fraction": {
        "mean": ("negativity_positive_fraction",), "stderr": (),
        "label": r"$P(\mathcal{N}>0)$", "ceiling": 1.0, "entropy_like": False,
        "kind": "quantum",
    },
    "S_A": {
        "mean": ("S_A_mean",), "stderr": ("S_A_stderr",),
        "label": r"$S_A$", "ceiling": LOG2, "entropy_like": True, "kind": "survival",
    },
    "S_B": {
        "mean": ("S_B_mean",), "stderr": ("S_B_stderr",),
        "label": r"$S_B$", "ceiling": LOG2, "entropy_like": True, "kind": "survival",
    },
}


def _metric_spec(name: str) -> dict[str, Any]:
    if name not in _STAGGER_METRICS:
        raise ValueError(
            f"Unknown two-probe mode-5 metric {name!r}. Choose one of {sorted(_STAGGER_METRICS)}."
        )
    return _STAGGER_METRICS[name]


def _load_stagger_file(
    path: Path,
    *,
    metrics: Sequence[str],
    mi_scale: float,
    l_by_file: Mapping[str, int] | None,
) -> dict[str, Any]:
    """Read one two-probe mode-5 CSV into ``(r, Delta, s)`` grids per metric."""
    df = pd.read_csv(path)
    if df.empty:
        raise ValueError(f"{path}: two-probe mode-5 CSV is empty.")

    metadata = resolve_metadata(df, path, l_by_file=l_by_file)
    r_col = _find_column(df, ["r", "separation", "distance"])
    delta_col = _find_column(df, ["delta", "insertion_delay"])
    s_col = _find_column(df, ["s", "tau", "elapsed_time"])
    t_eq_col = _find_column(df, ["t_eq", "teq"], required=False)

    columns = {
        "r": pd.to_numeric(df[r_col], errors="coerce"),
        "delta": pd.to_numeric(df[delta_col], errors="coerce"),
        "s": pd.to_numeric(df[s_col], errors="coerce"),
    }
    for name in metrics:
        spec = _metric_spec(name)
        mean_col = _find_column(df, spec["mean"])
        scale = mi_scale if spec["entropy_like"] else 1.0
        columns[f"{name}_mean"] = pd.to_numeric(df[mean_col], errors="coerce") * scale
        stderr_col = _find_column(df, spec["stderr"], required=False) if spec["stderr"] else None
        columns[f"{name}_stderr"] = (
            pd.to_numeric(df[stderr_col], errors="coerce") * scale
            if stderr_col is not None
            else pd.Series(np.nan, index=df.index)
        )

    clean = (
        pd.DataFrame(columns)
        .replace([np.inf, -np.inf], np.nan)
        .dropna(subset=["r", "delta", "s"])
        .sort_values(["r", "delta", "s"])
        .drop_duplicates(["r", "delta", "s"], keep="last")
    )
    if clean.empty:
        raise ValueError(f"{path}: no usable rows.")

    separations = np.sort(clean["r"].unique()).astype(int)
    delays = np.sort(clean["delta"].unique()).astype(int)
    times = np.sort(clean["s"].unique()).astype(int)

    index = pd.MultiIndex.from_product([separations, delays, times], names=["r", "delta", "s"])
    indexed = clean.set_index(["r", "delta", "s"]).reindex(index)
    shape = (separations.size, delays.size, times.size)
    grids = {
        name: {
            "mean": indexed[f"{name}_mean"].to_numpy(dtype=float).reshape(shape),
            "stderr": indexed[f"{name}_stderr"].to_numpy(dtype=float).reshape(shape),
        }
        for name in metrics
    }

    t_eq = None
    if t_eq_col is not None:
        values = pd.to_numeric(df[t_eq_col], errors="coerce").dropna().unique()
        if len(values) == 1:
            t_eq = int(round(float(values[0])))

    return {
        "path": path,
        "L": int(metadata["L"]),
        "p": float(metadata["p"]),
        "circuit": metadata["circuit"],
        "realizations": metadata["realizations"],
        "t_eq": t_eq,
        "r": separations,
        "delta": delays,
        "s": times,
        "grids": grids,
    }


def _mask_wrapped(dataset: dict[str, Any]) -> int:
    """Blank readouts a signal could only have reached by going the long way.

    Influence leaves ``x0`` at no more than one site per timestep, so the branch
    travelling away from ``B`` needs ``L - r`` timesteps to come round the ring
    and arrive from behind. The clock for that starts at ``A``'s insertion, and
    ``B`` was inserted ``Delta`` later, so the compromised cells are those with
    ``Delta + s >= L - r``. Blanking is per ``(r, Delta)`` rather than a global
    cut on ``s``: a flat cut would throw away most of the usable window at
    exactly the small separations the breakpoint fit depends on.

    Returns the number of grid cells blanked.
    """
    size = dataset["L"]
    total = dataset["delta"][None, :, None] + dataset["s"][None, None, :]
    reach = size - dataset["r"][:, None, None]
    wrapped = np.broadcast_to(total >= reach, next(iter(dataset["grids"].values()))["mean"].shape)
    for grid in dataset["grids"].values():
        grid["mean"] = np.where(wrapped, np.nan, grid["mean"])
        grid["stderr"] = np.where(wrapped, np.nan, grid["stderr"])
    return int(wrapped.sum())


def _threshold_level(
    spec: Mapping[str, Any], threshold: float, reference: str, mi_scale: float, peak: float
) -> float:
    """Turn a fractional threshold into the metric's own units.

    ``reference`` decides what the fraction is *of*, and the choice matters more
    than it looks. Against the theoretical ``ceiling`` a shared ``q`` does not
    mean the same thing for two channels that saturate at different fractions of
    it: at L=16, p=0.16 the observed peak is 10% of the ceiling for ``J`` but
    only 4% for the negativity, so ``q=0.02`` sits at 19% of one channel's range
    and 46% of the other's -- and the negativity then fails to cross at all over
    most of the grid, which reads as a missing front rather than as a badly
    placed threshold. Against the observed ``peak`` the same ``q`` is the same
    fraction of each channel's dynamic range, which is what makes the two
    arrival times comparable and is therefore the default.
    """
    scale = mi_scale if spec["entropy_like"] else 1.0
    if reference == "absolute":
        return float(threshold)
    if reference == "peak":
        return float(threshold) * float(peak)
    return float(threshold) * float(spec["ceiling"]) * scale


def _arrival_surface(
    dataset: Mapping[str, Any],
    metric: str,
    level: float,
    *,
    persistence: int,
) -> dict[str, np.ndarray]:
    """Arrival time ``s_arr`` and its error over the whole ``(r, Delta)`` grid."""
    grid = dataset["grids"][metric]
    shape = (dataset["r"].size, dataset["delta"].size)
    arrivals = np.full(shape, np.nan)
    errors = np.full(shape, np.nan)
    for r_index in range(shape[0]):
        for delta_index in range(shape[1]):
            arrivals[r_index, delta_index], errors[r_index, delta_index] = _arrival_times(
                dataset["s"],
                grid["mean"][r_index, delta_index, :],
                grid["stderr"][r_index, delta_index, :],
                level,
                persistence=persistence,
            )
    return {"arrival": arrivals, "arrival_stderr": errors}


def _fit_hinge(
    delays: np.ndarray, arrivals: np.ndarray, errors: np.ndarray, *, free_baseline: bool = True
) -> dict[str, float]:
    """Fit ``s = b + d*Delta + c * max(Delta_c - Delta, 0)`` for the breakpoint.

    The breakpoint is the only parameter the model is nonlinear in, so it is
    swept on a grid and the linear coefficients solved exactly by weighted least
    squares at each candidate. That is both more robust than a gradient method
    on a piecewise-linear objective and cheap enough not to matter.

    **The baseline slope ``d`` has to be free.** The protocol's model is a ramp
    falling onto a flat plateau, and forcing ``d = 0`` to match it is what makes
    this fit return nothing on real data. ``A`` sits in the circuit for
    ``Delta + s`` timesteps against ``B``'s ``s``, so the measurement record
    erodes what ``A`` holds and every arrival time drifts *later* as the delay
    grows -- the plateau rises. Superimposed on the geometric ramp that gives
    slope ``d - c`` before the breakpoint and ``d`` after it, so the kink is
    still exactly at ``Delta_c = lambda r``; only the assumption that the second
    segment is horizontal is wrong. Measured at L=16, p=0.16, 1200 realizations,
    the flat model fits nothing at r=2 or r=3 while the free one recovers
    ``Delta_c`` = 1.0 / 2.0 / 3.0 at r = 2 / 3 / 4 with ``d`` around +0.5.

    Pass ``free_baseline=False`` to recover the protocol's literal model, which
    is worth doing as a check when the probe decay is negligible.

    The sweep deliberately extends one delay step past the sampled range: a fit
    that wants a breakpoint outside the scanned window is reported as such
    rather than silently pinned to the edge, since that is the signature of a
    ``delta_max`` that was set too small.
    """
    valid = np.isfinite(delays) & np.isfinite(arrivals)
    x = delays[valid].astype(float)
    y = arrivals[valid].astype(float)
    sigma = errors[valid].astype(float)
    sigma = np.where(np.isfinite(sigma) & (sigma > 0.0), sigma, 1.0)
    parameters = 3 if free_baseline else 2
    failed = {
        "breakpoint": np.nan, "breakpoint_stderr": np.nan, "plateau": np.nan,
        "baseline_slope": np.nan, "ramp_slope": np.nan, "reduced_chi2": np.nan,
        "points": int(x.size),
    }
    # The linear coefficients plus the breakpoint, and the shape is only
    # meaningful with points on both segments.
    if x.size < parameters + 2:
        return failed

    weights = 1.0 / sigma**2
    span = float(x.max() - x.min())
    step = span / max(x.size - 1, 1)
    candidates = np.linspace(x.min() - step, x.max() + step, 401)

    best = None
    chi2_by_candidate = np.full(candidates.size, np.inf)
    for index, breakpoint in enumerate(candidates):
        ramp = np.maximum(breakpoint - x, 0.0)
        if np.count_nonzero(ramp > 0.0) < 2 or np.count_nonzero(ramp == 0.0) < 2:
            continue
        columns = [np.ones_like(x)] + ([x] if free_baseline else []) + [ramp]
        design = np.column_stack(columns)
        weighted = design * weights[:, None]
        normal = design.T @ weighted
        try:
            solution = np.linalg.solve(normal, weighted.T @ y)
        except np.linalg.LinAlgError:
            continue
        residual = y - design @ solution
        chi2 = float(np.sum(weights * residual**2))
        chi2_by_candidate[index] = chi2
        # A non-positive ramp coefficient means the arrival time does not fall
        # any faster before the candidate than after it, so there is no
        # breakpoint there -- the candidate stays in the chi^2 profile for the
        # error bar but cannot be the fit.
        if solution[-1] <= 0.0:
            continue
        if best is None or chi2 < best[0]:
            best = (
                chi2,
                float(breakpoint),
                float(solution[0]),
                float(solution[1]) if free_baseline else 0.0,
                float(solution[-1]),
            )

    if best is None:
        return failed

    chi2_min, breakpoint, plateau, baseline_slope, ramp_slope = best
    degrees = max(x.size - parameters - 1, 1)
    # Standard 1-sigma interval: the half-width of the chi^2 + 1 region, scaled
    # by the fit quality so an over- or under-estimated point error does not
    # translate directly into an over- or under-confident breakpoint.
    inflation = max(np.sqrt(chi2_min / degrees), 1.0)
    inside = candidates[chi2_by_candidate <= chi2_min + 1.0]
    breakpoint_stderr = (
        0.5 * float(inside.max() - inside.min()) * inflation if inside.size > 1 else step * inflation
    )
    return {
        "breakpoint": breakpoint,
        "breakpoint_stderr": breakpoint_stderr,
        "plateau": plateau,
        "baseline_slope": baseline_slope,
        "ramp_slope": ramp_slope,
        "reduced_chi2": chi2_min / degrees,
        "points": int(x.size),
    }


def _r_slope_profile(
    separations: np.ndarray, surface: Mapping[str, np.ndarray], delays: np.ndarray
) -> dict[str, np.ndarray]:
    """``d s_arr / d r`` at each fixed delay, with its error.

    This is the readout to fall back on when the hinge fits come back empty, and
    it is worth computing even when they do not.

    The reason is a confound the protocol warns about but which turns out to
    dominate: ``A`` sits in the circuit for ``Delta + s`` timesteps against
    ``B``'s ``s``, so the measurement record erodes what ``A`` holds, and the
    correlation at *every* separation decays with ``Delta``. That decay pushes
    ``s_arr`` up while the geometric ramp pushes it down, and at ``r`` below
    about ``L/4`` the decay wins -- so ``s_arr(Delta)`` at fixed ``r`` can rise
    monotonically and expose no breakpoint at all.

    At *fixed* ``Delta`` the decay is a common factor across separations, so it
    cancels out of the slope in ``r``. What survives is the geometry: the slope
    equals ``lambda`` while the front is still crossing the window and falls to
    zero once ``Delta`` exceeds ``lambda * r`` for every ``r`` in it. The delay
    at which it vanishes is therefore ``lambda * r_max``, one-way and free of the
    factor-of-two ambiguity -- the same thing the breakpoint is after, read off
    an axis the probe decay does not contaminate.
    """
    slopes = np.full(delays.size, np.nan)
    errors = np.full(delays.size, np.nan)
    x = separations.astype(float)
    for index in range(delays.size):
        y = surface["arrival"][:, index]
        sigma = surface["arrival_stderr"][:, index]
        finite = np.isfinite(y) & np.isfinite(x)
        if np.count_nonzero(finite) < 3:
            continue
        weights = np.where(np.isfinite(sigma[finite]) & (sigma[finite] > 0.0), sigma[finite], 1.0)
        fit = _weighted_linear_fit(x[finite], y[finite], weights)
        slopes[index] = fit["slope"]
        errors[index] = fit["slope_stderr"]
    return {"delta": delays.astype(float), "slope": slopes, "slope_stderr": errors}


def _fit_breakpoints(
    separations: np.ndarray, breakpoints: np.ndarray, errors: np.ndarray
) -> dict[str, float]:
    """Fit ``Delta_c(r) = b' + lambda r`` and invert the slope into a velocity."""
    valid = np.isfinite(breakpoints) & np.isfinite(separations)
    x = separations[valid].astype(float)
    y = breakpoints[valid].astype(float)
    sigma = errors[valid].astype(float)
    sigma = np.where(np.isfinite(sigma) & (sigma > 0.0), sigma, 1.0)
    if x.size < 3:
        return {
            "slope": np.nan, "slope_stderr": np.nan, "intercept": np.nan,
            "intercept_stderr": np.nan, "reduced_chi2": np.nan,
            "velocity": np.nan, "velocity_stderr": np.nan, "points": int(x.size),
        }
    fit = _weighted_linear_fit(x, y, sigma)
    slope = fit["slope"]
    velocity = 1.0 / slope if slope > 0.0 else np.nan
    velocity_stderr = fit["slope_stderr"] / slope**2 if slope > 0.0 else np.nan
    return {**fit, "velocity": velocity, "velocity_stderr": velocity_stderr, "points": int(x.size)}


def stagger_velocity(
    files: Sequence[str | Path] | str | Path | None = None,
    *,
    file_glob: str | Path | None = None,
    classical_metric: str = "J",
    quantum_metric: str = "negativity",
    threshold: float = 0.02,
    reference: str = "peak",
    r_min: int | None = None,
    r_max: int | None = None,
    s_max: int | None = None,
    delta_parity: str = "both",
    drop_wrapped: bool = True,
    s_a_floor: float | None = None,
    persistence: int = 2,
    heatmap_file: str | Path | None = None,
    heatmap_delta: int = 0,
    heatmap_r: int | None = None,
    mi_units: str = "nats",
    cmap: str = "magma",
    l_by_file: Mapping[str, int] | None = None,
    figsize: tuple[float, float] = (13.0, 13.5),
    dpi: int = 130,
    show: bool = True,
) -> dict[str, Any]:
    """Extract one-way propagation velocities from staggered two-probe output.

    Parameters
    ----------
    files, file_glob:
        One two-probe mode-5 CSV per system size. The heatmaps come from a
        single file (``heatmap_file``, or the largest ``L``); the breakpoint
        fits use all of them.
    classical_metric, quantum_metric:
        Which observable stands for each channel. ``J`` is the optimized
        classical correlation and needs a run with the measurement optimization
        enabled; ``C_max`` is the three-axis lower bound and always present.
        ``C_Z`` is the superselection-safe choice for fermionic circuits.
    threshold, reference:
        Signal level ``q``, as a fraction of what ``reference`` names:
        ``"peak"`` (default) the largest value the metric reaches anywhere on
        the surviving grid, ``"ceiling"`` its theoretical maximum, or
        ``"absolute"`` for a raw value in the metric's own units. Prefer
        ``"peak"``: the classical and quantum channels saturate at very
        different fractions of their ceilings, so a shared ``q`` against the
        ceiling silently makes the threshold far stricter for one of them. See
        :func:`_threshold_level`. With ``"peak"``, ``q`` around 0.2 sits in the
        middle of the rise.
    r_min, r_max, s_max:
        Windows on separation and readout time. Small separations are the ones
        with the most signal; large ones approach the antipode, where both arcs
        of the ring carry influence and ``r`` stops labelling a single path.
    delta_parity:
        ``"both"`` (default), ``"even"``, or ``"odd"``. Arrival times oscillate
        with the parity of the insertion delay because consecutive delays place
        ``B`` in brickwork layers of opposite bond parity. Fitting each parity
        separately is the check that the oscillation is adding scatter to
        ``Delta_c`` rather than bias.
    drop_wrapped:
        Blank each ``(r, Delta)`` once influence could have reached ``B`` the
        long way round the ring, at ``Delta + s >= L - r``.
    s_a_floor:
        Blank cells where ``A`` has purified below this fraction of ``log 2``.
        ``A`` sits in the circuit for ``Delta + s`` timesteps while ``B`` sits
        there for ``s``, so at large delay the measurement record can have
        destroyed most of what ``A`` held and the vanishing correlation says
        that rather than saying the signal has not arrived. A floor near ``0.5``
        keeps the delay window honest; ``None`` (the default) applies no cut,
        since ``S_A`` is in the CSV and worth looking at first.
    persistence:
        Consecutive readout times a crossing must hold for to count as an
        arrival.

    Returns a dictionary with the figure, its axes, the loaded grids, the
    per-``(metric, r, L)`` arrival surfaces and hinge fits, the fitted
    ``Delta_c(r)`` lines, and the fitted gap between the two channels.

    ``result["r_slope"][(metric, L)]`` holds ``d s_arr / d r`` against delay,
    which extracts the same one-way ``lambda`` without the probe-decay confound
    that can empty the hinge fits entirely. Read :func:`_r_slope_profile` before
    concluding that a null breakpoint means no front.
    """
    paths = _resolve_files(files, file_glob)
    unit_label, mi_scale = _mi_unit_spec(mi_units)
    metrics = [classical_metric, quantum_metric]
    for name in metrics:
        _metric_spec(name)
    if classical_metric == quantum_metric:
        raise ValueError("classical_metric and quantum_metric must differ.")
    if reference not in ("peak", "ceiling", "absolute"):
        raise ValueError("reference must be 'peak', 'ceiling', or 'absolute'.")
    if reference != "absolute" and not 0.0 < threshold < 1.0:
        raise ValueError("A fractional threshold must lie strictly between 0 and 1.")
    if persistence < 1:
        raise ValueError("persistence must be at least 1.")
    if delta_parity not in ("both", "even", "odd"):
        raise ValueError("delta_parity must be 'both', 'even', or 'odd'.")
    if s_a_floor is not None and not 0.0 <= s_a_floor < 1.0:
        raise ValueError("s_a_floor is a fraction of log 2 and must lie in [0, 1).")

    loaded_metrics = list(metrics)
    if s_a_floor is not None and "S_A" not in loaded_metrics:
        loaded_metrics.append("S_A")
    datasets = [
        _load_stagger_file(path, metrics=loaded_metrics, mi_scale=mi_scale, l_by_file=l_by_file)
        for path in paths
    ]
    datasets.sort(key=lambda dataset: dataset["L"])

    for dataset in datasets:
        for name in metrics:
            if not np.isfinite(dataset["grids"][name]["mean"]).any():
                extra = (
                    " Re-run with MIPT_PROBED_DISCORD=1, or use classical_metric='C_max'."
                    if name in ("J", "discord")
                    else ""
                )
                raise ValueError(f"{dataset['path']}: {name} is entirely missing.{extra}")
        # Trim before anything is fitted so the heatmaps and the arrival times
        # always describe the same data.
        if s_max is not None:
            keep = dataset["s"] <= s_max
            if not keep.any():
                raise ValueError(f"{dataset['path']}: no readout times survive s <= {s_max}.")
            dataset["s"] = dataset["s"][keep]
            for grid in dataset["grids"].values():
                grid["mean"] = grid["mean"][:, :, keep]
                grid["stderr"] = grid["stderr"][:, :, keep]
        if drop_wrapped:
            _mask_wrapped(dataset)
        if s_a_floor is not None:
            purified = dataset["grids"]["S_A"]["mean"] < s_a_floor * LOG2 * mi_scale
            for name in metrics:
                grid = dataset["grids"][name]
                grid["mean"] = np.where(purified, np.nan, grid["mean"])
                grid["stderr"] = np.where(purified, np.nan, grid["stderr"])

    # The peak is taken after masking, so a cell the wrap or purification cut
    # removed cannot set the scale for the cells that survived.
    peaks = {
        name: float(
            np.nanmax(
                [
                    np.nanmax(dataset["grids"][name]["mean"])
                    if np.isfinite(dataset["grids"][name]["mean"]).any()
                    else np.nan
                    for dataset in datasets
                ]
            )
        )
        for name in metrics
    }
    levels = {
        name: _threshold_level(_metric_spec(name), threshold, reference, mi_scale, peaks[name])
        for name in metrics
    }

    # A threshold below the sampling noise is not a front, it is a coin flip.
    # Cells before any signal arrives are identically zero in every trajectory,
    # so their standard error is zero up to round-off; including them would drag
    # the median to round-off scale and the check would never fire.
    noise_floor: dict[str, float] = {}
    for name in metrics:
        spec = _metric_spec(name)
        ceiling = spec["ceiling"] * (mi_scale if spec["entropy_like"] else 1.0)
        errors = np.concatenate([dataset["grids"][name]["stderr"].ravel() for dataset in datasets])
        errors = errors[np.isfinite(errors) & (errors > 1.0e-9 * ceiling)]
        noise_floor[name] = float(np.median(errors)) if errors.size else np.nan
        if np.isfinite(noise_floor[name]) and levels[name] < 2.0 * noise_floor[name]:
            warnings.warn(
                f"The q={threshold:g} level for {name} ({levels[name]:.3g}) is below twice the "
                f"sampling noise ({noise_floor[name]:.3g}); arrival times will be dominated by "
                "fluctuations. Raise the threshold or the realization count."
            )

    surfaces: dict[tuple[str, int], dict[str, np.ndarray]] = {}
    r_slopes: dict[tuple[str, int], dict[str, np.ndarray]] = {}
    hinges: dict[tuple[str, int, int], dict[str, float]] = {}
    breakpoint_curves: dict[tuple[str, int], dict[str, np.ndarray]] = {}
    breakpoint_fits: dict[tuple[str, int], dict[str, float]] = {}
    for dataset in datasets:
        delays = dataset["delta"]
        if delta_parity == "even":
            delay_keep = delays % 2 == 0
        elif delta_parity == "odd":
            delay_keep = delays % 2 == 1
        else:
            delay_keep = np.ones(delays.size, dtype=bool)

        separation_keep = np.ones(dataset["r"].size, dtype=bool)
        if r_min is not None:
            separation_keep &= dataset["r"] >= r_min
        if r_max is not None:
            separation_keep &= dataset["r"] <= r_max

        for name in metrics:
            surface = _arrival_surface(dataset, name, levels[name], persistence=persistence)
            surfaces[(name, dataset["L"])] = surface
            r_slopes[(name, dataset["L"])] = _r_slope_profile(
                dataset["r"][separation_keep],
                {
                    "arrival": surface["arrival"][separation_keep, :],
                    "arrival_stderr": surface["arrival_stderr"][separation_keep, :],
                },
                delays,
            )

            separations, values, sigmas = [], [], []
            for r_index, separation in enumerate(dataset["r"]):
                fit = _fit_hinge(
                    delays[delay_keep],
                    surface["arrival"][r_index, delay_keep],
                    surface["arrival_stderr"][r_index, delay_keep],
                )
                hinges[(name, int(separation), dataset["L"])] = fit
                if not separation_keep[r_index]:
                    continue
                separations.append(float(separation))
                values.append(fit["breakpoint"])
                sigmas.append(fit["breakpoint_stderr"])
            curve = {
                "r": np.asarray(separations, dtype=float),
                "breakpoint": np.asarray(values, dtype=float),
                "breakpoint_stderr": np.asarray(sigmas, dtype=float),
            }
            breakpoint_curves[(name, dataset["L"])] = curve
            breakpoint_fits[(name, dataset["L"])] = _fit_breakpoints(
                curve["r"], curve["breakpoint"], curve["breakpoint_stderr"]
            )
            resolved = int(np.isfinite(curve["breakpoint"]).sum())
            if resolved < 3:
                warnings.warn(
                    f"L={dataset['L']}: {name} resolved a breakpoint at only {resolved} "
                    "separation(s), too few to fit lambda. This is often the probe-decay "
                    "confound rather than a statistics problem -- check result['r_slope'] "
                    f"[('{name}', {dataset['L']})], which cancels it. See _r_slope_profile."
                )

    # The gap between the two channels, separation by separation.
    gaps: dict[int, dict[str, np.ndarray]] = {}
    gap_fits: dict[int, dict[str, float]] = {}
    separations, differences, gap_errors = [], [], []
    for dataset in datasets:
        classical = breakpoint_curves[(classical_metric, dataset["L"])]
        quantum = breakpoint_curves[(quantum_metric, dataset["L"])]
        shared = np.intersect1d(classical["r"], quantum["r"])
        for separation in shared:
            c_index = int(np.flatnonzero(classical["r"] == separation)[0])
            q_index = int(np.flatnonzero(quantum["r"] == separation)[0])
            difference = quantum["breakpoint"][q_index] - classical["breakpoint"][c_index]
            if not np.isfinite(difference):
                continue
            sigma = float(
                np.sqrt(
                    np.nansum(
                        [
                            classical["breakpoint_stderr"][c_index] ** 2,
                            quantum["breakpoint_stderr"][q_index] ** 2,
                        ]
                    )
                )
            )
            separations.append(float(separation))
            differences.append(float(difference))
            gap_errors.append(sigma if sigma > 0.0 else 1.0)
    gap = {
        "r": np.asarray(separations, dtype=float),
        "delta_gap": np.asarray(differences, dtype=float),
        "delta_gap_stderr": np.asarray(gap_errors, dtype=float),
    }
    gap_fit = _fit_breakpoints(gap["r"], gap["delta_gap"], gap["delta_gap_stderr"])

    # ----------------------------------------------------------------- figure
    heatmap_dataset = datasets[-1]
    if heatmap_file is not None:
        wanted = Path(heatmap_file)
        matches = [dataset for dataset in datasets if dataset["path"] == wanted]
        if not matches:
            raise ValueError(f"{heatmap_file} is not among the loaded files.")
        heatmap_dataset = matches[0]
    if heatmap_delta not in set(heatmap_dataset["delta"].tolist()):
        raise ValueError(
            f"heatmap_delta={heatmap_delta} is not in the scanned delays "
            f"{heatmap_dataset['delta'].tolist()}."
        )
    reference_r = int(heatmap_r if heatmap_r is not None else heatmap_dataset["r"].max())
    if reference_r not in set(heatmap_dataset["r"].tolist()):
        raise ValueError(
            f"heatmap_r={reference_r} is not in the scanned separations "
            f"{heatmap_dataset['r'].tolist()}."
        )
    delta_index = int(np.flatnonzero(heatmap_dataset["delta"] == heatmap_delta)[0])
    r_index = int(np.flatnonzero(heatmap_dataset["r"] == reference_r)[0])

    fig, axes = plt.subplots(3, 2, figsize=figsize, dpi=dpi, constrained_layout=True)
    (ax_cl_rs, ax_qu_rs), (ax_cl_ds, ax_qu_ds), (ax_breakpoint, ax_gap) = axes

    # One normalization for all four heatmaps, so the classical and quantum
    # channels are directly comparable and the two rows are comparable too. The
    # floor is the sampling noise rather than the smallest cell: ranging down to
    # the smallest value spends the ramp resolving cells that are all
    # statistically zero, which reads as structure that is not there.
    # Display uses exactly the normalizer the threshold used, so the white
    # contour always sits at q on the colour scale whatever `reference` is.
    display_scale = {
        name: (levels[name] / threshold if reference != "absolute" else 1.0) for name in metrics
    }
    floors, ceilings = [], []
    for name in metrics:
        scaled = heatmap_dataset["grids"][name]["mean"] / display_scale[name]
        positive = scaled[np.isfinite(scaled) & (scaled > 0.0)]
        if positive.size:
            ceilings.append(float(positive.max()))
        floor = noise_floor[name]
        if np.isfinite(floor) and floor > 0.0:
            floors.append(floor / display_scale[name])
    vmin = max(min(floors) if floors else 1e-4, 1e-6)
    vmax = max(ceilings) if ceilings else 1.0
    norm = LogNorm(vmin=vmin, vmax=max(vmax, vmin * 10.0))

    mesh = None
    panels = (
        (ax_cl_rs, classical_metric, "r"),
        (ax_qu_rs, quantum_metric, "r"),
        (ax_cl_ds, classical_metric, "delta"),
        (ax_qu_ds, quantum_metric, "delta"),
    )
    for ax, name, axis in panels:
        spec = _metric_spec(name)
        color = _CLASSICAL_COLOR if name == classical_metric else _QUANTUM_COLOR
        if axis == "r":
            scaled = heatmap_dataset["grids"][name]["mean"][:, delta_index, :] / display_scale[name]
            horizontal = heatmap_dataset["r"]
            ax.set_xlabel(r"Probe separation, $r$ (sites)")
            ax.set_title(rf"{spec['label']} at $\Delta={heatmap_delta}$")
        else:
            scaled = heatmap_dataset["grids"][name]["mean"][r_index, :, :] / display_scale[name]
            horizontal = heatmap_dataset["delta"]
            ax.set_xlabel(r"Insertion delay, $\Delta$ (timesteps)")
            ax.set_title(rf"{spec['label']} at $r={reference_r}$")
        mesh = ax.pcolormesh(
            horizontal, heatmap_dataset["s"], scaled.T, shading="auto", cmap=cmap, norm=norm
        )
        if vmin < threshold < vmax and np.isfinite(scaled).any():
            contours = ax.contour(
                horizontal, heatmap_dataset["s"], scaled.T,
                levels=[threshold], colors="white", linewidths=1.2,
            )
            ax.clabel(contours, fmt=lambda value: f"q={value:g}", fontsize=7.5, inline=True)
        ax.set_ylabel(r"Elapsed time after $B$, $s$")

        # The measured arrival curve, drawn on top of the field it came from.
        surface = surfaces[(name, heatmap_dataset["L"])]
        if axis == "r":
            arrivals = surface["arrival"][:, delta_index]
            arrival_errors = surface["arrival_stderr"][:, delta_index]
        else:
            arrivals = surface["arrival"][r_index, :]
            arrival_errors = surface["arrival_stderr"][r_index, :]
        finite = np.isfinite(arrivals)
        if finite.any():
            ax.errorbar(
                np.asarray(horizontal, dtype=float)[finite], arrivals[finite],
                yerr=arrival_errors[finite], color=color, marker="o", markersize=4.0,
                linestyle="none", capsize=2, elinewidth=1.0, markeredgecolor="white",
                markeredgewidth=0.6,
            )
        if axis == "delta":
            hinge = hinges.get((name, reference_r, heatmap_dataset["L"]))
            if hinge is not None and np.isfinite(hinge["breakpoint"]):
                line_x = np.linspace(float(horizontal.min()), float(horizontal.max()), 128)
                ax.plot(
                    line_x,
                    hinge["plateau"] + hinge["ramp_slope"] * np.maximum(hinge["breakpoint"] - line_x, 0.0),
                    color=color, linewidth=1.8,
                )
                ax.axvline(hinge["breakpoint"], color=color, linewidth=1.2, linestyle="--")

    if mesh is not None:
        colorbar = fig.colorbar(mesh, ax=[ax_cl_rs, ax_qu_rs, ax_cl_ds, ax_qu_ds],
                                location="right", pad=0.015)
        colorbar.set_label(f"Signal, as a fraction of the metric {reference}")

    markers = ["o", "s", "^", "D", "v", "P"]
    # The headline result is the two channels agreeing, which would hide one
    # series completely underneath the other. Dodge them apart by a fraction of
    # a lattice site so an exact coincidence still reads as two measurements.
    dodges = (-0.035, +0.035)
    for channel_index, (name, color) in enumerate(
        ((classical_metric, _CLASSICAL_COLOR), (quantum_metric, _QUANTUM_COLOR))
    ):
        for size_index, dataset in enumerate(datasets):
            curve = breakpoint_curves[(name, dataset["L"])]
            fit = breakpoint_fits[(name, dataset["L"])]
            finite = np.isfinite(curve["breakpoint"])
            if not finite.any():
                continue
            ax_breakpoint.errorbar(
                curve["r"][finite] + dodges[channel_index], curve["breakpoint"][finite],
                yerr=curve["breakpoint_stderr"][finite], color=color,
                marker=markers[size_index % len(markers)], markersize=5.0,
                linestyle="none", capsize=2, elinewidth=1.0,
            )
            if np.isfinite(fit["slope"]):
                line_x = np.linspace(curve["r"][finite].min(), curve["r"][finite].max(), 64)
                ax_breakpoint.plot(
                    line_x, fit["intercept"] + fit["slope"] * line_x, color=color, linewidth=2.0,
                    linestyle="-" if channel_index == 0 else (0, (5, 3)),
                )
    ax_breakpoint.plot([], [], color=_CLASSICAL_COLOR, linewidth=2.0,
                       label=f"classical, {_metric_spec(classical_metric)['label']}")
    ax_breakpoint.plot([], [], color=_QUANTUM_COLOR, linewidth=2.0,
                       label=f"quantum, {_metric_spec(quantum_metric)['label']}")
    for size_index, dataset in enumerate(datasets):
        ax_breakpoint.plot(
            [], [], color="0.35", linestyle="none",
            marker=markers[size_index % len(markers)], markersize=5.0,
            label=rf"$L={dataset['L']}$",
        )
    ax_breakpoint.set_xlabel(r"Probe separation, $r$ (sites)")
    ax_breakpoint.set_ylabel(r"Breakpoint delay, $\Delta_{\mu,c}(r)$")
    ax_breakpoint.set_title(r"One-way velocity: $\Delta_c = b' + \lambda r$")
    ax_breakpoint.legend(fontsize=8, ncol=2)

    velocity_lines = []
    for name, channel in ((classical_metric, "classical"), (quantum_metric, "quantum")):
        estimates = [
            (breakpoint_fits[(name, dataset["L"])]["velocity"],
             breakpoint_fits[(name, dataset["L"])]["velocity_stderr"])
            for dataset in datasets
        ]
        finite = [(value, error) for value, error in estimates if np.isfinite(value)]
        if not finite:
            continue
        values = np.array([value for value, _ in finite])
        spread = float(values.std(ddof=1)) if values.size > 1 else float(finite[0][1])
        velocity_lines.append(rf"$v_{{\rm {channel}}} = {values.mean():.2f} \pm {spread:.2f}$")
    if velocity_lines:
        _annotate_axes(ax_breakpoint, "\n".join(velocity_lines), "upper left", fontsize=8)

    if gap["r"].size:
        ax_gap.errorbar(
            gap["r"], gap["delta_gap"], yerr=gap["delta_gap_stderr"], color=_QUANTUM_COLOR,
            marker="o", markersize=5.0, linestyle="none", capsize=2, elinewidth=1.0,
        )
        if np.isfinite(gap_fit["slope"]):
            line_x = np.linspace(gap["r"].min(), gap["r"].max(), 64)
            ax_gap.plot(
                line_x, gap_fit["intercept"] + gap_fit["slope"] * line_x,
                color=_QUANTUM_COLOR, linewidth=2.0,
            )
    ax_gap.axhline(0.0, color="0.5", linewidth=1.0, linestyle=":")
    ax_gap.set_xlabel(r"Probe separation, $r$ (sites)")
    ax_gap.set_ylabel(r"$\Delta_{\mathcal{N},c} - \Delta_{J,c}$")
    ax_gap.set_title("Quantum-minus-classical breakpoint")

    if np.isfinite(gap_fit["slope"]):
        significant = (
            np.isfinite(gap_fit["slope_stderr"]) and abs(gap_fit["slope"]) > 2.0 * gap_fit["slope_stderr"]
        )
        verdict = (
            "grows: different velocities"
            if significant and gap_fit["slope"] > 0.0
            else "shrinks" if significant else "flat: one velocity, fixed formation delay"
        )
        _annotate_axes(
            ax_gap,
            rf"$d\Delta_c/dr = {gap_fit['slope']:.3f} \pm {gap_fit['slope_stderr']:.3f}$"
            f"\n({verdict})",
            "upper left",
            fontsize=8,
        )

    first = datasets[0]
    fig.suptitle(
        f"Staggered two-probe velocities, {first['circuit']}, "
        rf"$p={first['p']:g}$, $q={threshold:g}$ of {reference}, $\Delta$ parity: {delta_parity}"
    )

    _show(fig, show)
    return {
        "figure": fig,
        "axes": axes,
        "datasets": datasets,
        "surfaces": surfaces,
        "r_slope": r_slopes,
        "hinges": hinges,
        "breakpoint_curves": breakpoint_curves,
        "breakpoint_fits": breakpoint_fits,
        "gap": gap,
        "gap_fit": gap_fit,
        "levels": levels,
        "noise_floor": noise_floor,
        "threshold": threshold,
        "reference": reference,
        "peaks": peaks,
        "classical_metric": classical_metric,
        "quantum_metric": quantum_metric,
        "delta_parity": delta_parity,
        "s_a_floor": s_a_floor,
        "mi_units": unit_label,
    }
