"""
fermionic_partial_trace.py

Dense fermionic partial tracing for Jordan-Wigner/occupation-basis statevectors
and density matrices.

This module is intended for small-to-moderate mode counts where the full
statevector or density matrix is already available. It does not depend on
Qiskit.  It treats computational-basis bit strings as fermionic occupation
strings and inserts the parity signs required when modes are reordered before
tracing.

Convention
----------
The canonical Fock basis is

    |n_0 n_1 ... n_{N-1}> = (c_0^dagger)^n0 (c_1^dagger)^n1 ... |vac>

up to the selected integer-index convention:

    basis_order="little": integer index = sum_m n_m 2^m
        This matches Qiskit's statevector array convention when mode m is qubit m.

    basis_order="big": integer index = sum_m n_m 2^(N-1-m)
        This is the textbook left-to-right bit-string convention.

For an arbitrary kept mode list, the implementation first changes from the
canonical mode order [0,1,...,N-1] to [keep..., traced...] with the fermionic
sign generated by permuting occupied creation operators.  It then performs an
ordinary trace over the traced suffix.  The returned matrix is in the Fock basis
whose mode order is exactly the user-supplied `keep` order.

Main entry points
-----------------
    fermionic_partial_trace_statevector(psi, keep=[...])
    fermionic_partial_trace_density_matrix(rho, keep=[...])
    fermionic_reduced_density_matrix(obj, keep=[...])
    fermionic_tmi_from_statevector(psi, modes=(a,b,c))
    fermionic_tmi_from_density_matrix(rho, modes=(a,b,c))
    fermionic_tmi_from_reduced_3mode_density(rho_abc)

For repeated tracing of many states with the same subsystem, use
FermionicPartialTracePlan and reuse it.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from math import log
from typing import Iterable, Literal, Sequence

import numpy as np
from numpy.typing import NDArray

BasisOrder = Literal["little", "big"]
ComplexArray = NDArray[np.complex128]


class FermionicPartialTraceError(ValueError):
    """Raised for invalid fermionic partial-trace inputs."""


def _is_power_of_two(x: int) -> bool:
    return x > 0 and (x & (x - 1)) == 0


def _log2_int(x: int) -> int:
    if not _is_power_of_two(x):
        raise FermionicPartialTraceError(f"dimension {x} is not a power of two")
    return x.bit_length() - 1


def _infer_n_modes_from_statevector(psi: np.ndarray) -> int:
    if psi.ndim != 1:
        raise FermionicPartialTraceError(
            f"statevector must be one-dimensional, got shape {psi.shape}"
        )
    return _log2_int(int(psi.shape[0]))


def _infer_n_modes_from_density_matrix(rho: np.ndarray) -> int:
    if rho.ndim != 2 or rho.shape[0] != rho.shape[1]:
        raise FermionicPartialTraceError(
            f"density matrix must be square, got shape {rho.shape}"
        )
    return _log2_int(int(rho.shape[0]))


def _normalize_mode_list(
    *,
    keep: Sequence[int] | None,
    trace_out: Sequence[int] | None,
    n_modes: int,
) -> tuple[tuple[int, ...], tuple[int, ...]]:
    if keep is None and trace_out is None:
        raise FermionicPartialTraceError("provide either keep=... or trace_out=...")
    if keep is not None and trace_out is not None:
        raise FermionicPartialTraceError("provide only one of keep=... or trace_out=...")

    all_modes = tuple(range(n_modes))

    if keep is not None:
        keep_tuple = tuple(int(m) for m in keep)
        if len(set(keep_tuple)) != len(keep_tuple):
            raise FermionicPartialTraceError(f"duplicate modes in keep={keep_tuple}")
        bad = [m for m in keep_tuple if m < 0 or m >= n_modes]
        if bad:
            raise FermionicPartialTraceError(
                f"keep contains out-of-range modes {bad}; n_modes={n_modes}"
            )
        trace_tuple = tuple(m for m in all_modes if m not in set(keep_tuple))
        return keep_tuple, trace_tuple

    trace_tuple = tuple(int(m) for m in trace_out or ())
    if len(set(trace_tuple)) != len(trace_tuple):
        raise FermionicPartialTraceError(f"duplicate modes in trace_out={trace_tuple}")
    bad = [m for m in trace_tuple if m < 0 or m >= n_modes]
    if bad:
        raise FermionicPartialTraceError(
            f"trace_out contains out-of-range modes {bad}; n_modes={n_modes}"
        )
    keep_tuple = tuple(m for m in all_modes if m not in set(trace_tuple))
    return keep_tuple, trace_tuple


def _bit(index: int, slot: int, n_slots: int, basis_order: BasisOrder) -> int:
    if basis_order == "little":
        return (index >> slot) & 1
    if basis_order == "big":
        return (index >> (n_slots - 1 - slot)) & 1
    raise FermionicPartialTraceError(
        f"basis_order must be 'little' or 'big', got {basis_order!r}"
    )


def _index_from_occupations(occ_by_mode: Sequence[int], basis_order: BasisOrder) -> int:
    n_modes = len(occ_by_mode)
    idx = 0
    if basis_order == "little":
        for mode, occ in enumerate(occ_by_mode):
            if occ:
                idx |= 1 << mode
        return idx
    if basis_order == "big":
        for mode, occ in enumerate(occ_by_mode):
            if occ:
                idx |= 1 << (n_modes - 1 - mode)
        return idx
    raise FermionicPartialTraceError(
        f"basis_order must be 'little' or 'big', got {basis_order!r}"
    )


def _fermionic_reorder_sign(
    occ_by_mode: Sequence[int], new_mode_order: Sequence[int]
) -> int:
    """
    Sign for converting the canonical creation-operator order [0,1,...]
    into `new_mode_order`, for one occupation pattern.

    If
        |n>_canonical = s |n>_new_order,
    this returns s = +/-1.
    """
    pos_new = {mode: pos for pos, mode in enumerate(new_mode_order)}
    occupied_positions_in_new_order = [
        pos_new[mode] for mode, occ in enumerate(occ_by_mode) if occ
    ]

    inv_parity = 0
    length = len(occupied_positions_in_new_order)
    for i in range(length):
        ai = occupied_positions_in_new_order[i]
        for j in range(i + 1, length):
            if ai > occupied_positions_in_new_order[j]:
                inv_parity ^= 1
    return -1 if inv_parity else 1


@lru_cache(maxsize=4096)
def _basis_reorder_map_cached(
    n_modes: int,
    new_mode_order: tuple[int, ...],
    basis_order: BasisOrder,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Return arrays indexed by `new_idx`:
        old_index[new_idx] = corresponding canonical-basis index
        sign[new_idx]      = fermionic sign for |old> = sign |new>
    """
    if len(new_mode_order) != n_modes or set(new_mode_order) != set(range(n_modes)):
        raise FermionicPartialTraceError(
            f"new_mode_order must be a permutation of 0..{n_modes - 1}; "
            f"got {new_mode_order}"
        )

    dim = 1 << n_modes
    old_index = np.empty(dim, dtype=np.int64)
    sign = np.empty(dim, dtype=np.int8)

    for new_idx in range(dim):
        occ_by_mode = [0] * n_modes
        for slot, mode in enumerate(new_mode_order):
            occ_by_mode[mode] = _bit(new_idx, slot, n_modes, basis_order)

        old_index[new_idx] = _index_from_occupations(occ_by_mode, basis_order)
        sign[new_idx] = _fermionic_reorder_sign(occ_by_mode, new_mode_order)

    return old_index, sign


def _suffix_block_indices(
    keep_dim: int,
    trace_dim: int,
    trace_index: int,
    basis_order: BasisOrder,
) -> np.ndarray:
    """Indices whose kept part varies and traced suffix equals trace_index."""
    if basis_order == "little":
        # new_index = keep_index + keep_dim * trace_index
        return np.arange(keep_dim, dtype=np.int64) + keep_dim * trace_index
    if basis_order == "big":
        # new_index = keep_index * trace_dim + trace_index
        return np.arange(keep_dim, dtype=np.int64) * trace_dim + trace_index
    raise FermionicPartialTraceError(
        f"basis_order must be 'little' or 'big', got {basis_order!r}"
    )


@dataclass(frozen=True)
class FermionicPartialTracePlan:
    """
    Precomputed dense fermionic partial-trace plan.

    Parameters
    ----------
    n_modes:
        Number of fermionic modes in the input state.
    keep:
        Physical modes to keep. The returned reduced density matrix is in the
        Fock basis with this exact mode order.
    basis_order:
        Integer-index convention of the input array. Use "little" for Qiskit
        statevector arrays when qubit m stores fermionic mode m.

    Notes
    -----
    Reuse a plan when processing many states with the same kept subsystem.
    """

    n_modes: int
    keep: tuple[int, ...]
    basis_order: BasisOrder = "little"

    def __init__(
        self,
        n_modes: int,
        keep: Sequence[int] | None = None,
        *,
        trace_out: Sequence[int] | None = None,
        basis_order: BasisOrder = "little",
    ) -> None:
        keep_tuple, trace_tuple = _normalize_mode_list(
            keep=keep, trace_out=trace_out, n_modes=int(n_modes)
        )
        object.__setattr__(self, "n_modes", int(n_modes))
        object.__setattr__(self, "keep", keep_tuple)
        object.__setattr__(self, "trace_out", trace_tuple)
        object.__setattr__(self, "basis_order", basis_order)
        object.__setattr__(self, "keep_dim", 1 << len(keep_tuple))
        object.__setattr__(self, "trace_dim", 1 << len(trace_tuple))
        object.__setattr__(self, "new_mode_order", keep_tuple + trace_tuple)

        old_index, sign = _basis_reorder_map_cached(
            self.n_modes, self.new_mode_order, self.basis_order
        )
        object.__setattr__(self, "old_index", old_index)
        object.__setattr__(self, "sign", sign.astype(np.float64))

        block_indices = []
        block_old_indices = []
        block_signs = []
        for tr in range(self.trace_dim):
            new_idx = _suffix_block_indices(
                self.keep_dim, self.trace_dim, tr, self.basis_order
            )
            block_indices.append(new_idx)
            block_old_indices.append(old_index[new_idx])
            block_signs.append(sign[new_idx].astype(np.float64))

        object.__setattr__(self, "block_indices", tuple(block_indices))
        object.__setattr__(self, "block_old_indices", tuple(block_old_indices))
        object.__setattr__(self, "block_signs", tuple(block_signs))

    @property
    def n_keep(self) -> int:
        return len(self.keep)

    @property
    def n_trace(self) -> int:
        return len(self.trace_out)  # type: ignore[attr-defined]

    def trace_statevector(self, psi: np.ndarray) -> ComplexArray:
        """Return the reduced density matrix of `psi` on this plan's kept modes."""
        psi_arr = np.asarray(psi, dtype=np.complex128)
        n_from_psi = _infer_n_modes_from_statevector(psi_arr)
        if n_from_psi != self.n_modes:
            raise FermionicPartialTraceError(
                f"plan has n_modes={self.n_modes}, but statevector has {n_from_psi} modes"
            )

        out = np.zeros((self.keep_dim, self.keep_dim), dtype=np.complex128)
        for old_idx, signs in zip(self.block_old_indices, self.block_signs):
            amp = signs * psi_arr[old_idx]
            out += np.outer(amp, amp.conjugate())
        return out

    def trace_density_matrix(self, rho: np.ndarray) -> ComplexArray:
        """Return the reduced density matrix of `rho` on this plan's kept modes."""
        rho_arr = np.asarray(rho, dtype=np.complex128)
        n_from_rho = _infer_n_modes_from_density_matrix(rho_arr)
        if n_from_rho != self.n_modes:
            raise FermionicPartialTraceError(
                f"plan has n_modes={self.n_modes}, but density matrix has {n_from_rho} modes"
            )

        out = np.zeros((self.keep_dim, self.keep_dim), dtype=np.complex128)
        for old_idx, signs in zip(self.block_old_indices, self.block_signs):
            block = rho_arr[np.ix_(old_idx, old_idx)]
            out += (signs[:, None] * signs[None, :]) * block
        return out

    def reorder_statevector_to_keep_trace_order(self, psi: np.ndarray) -> ComplexArray:
        """
        Return the full statevector expressed in mode order [keep..., trace...].
        Mostly useful for debugging and validation.
        """
        psi_arr = np.asarray(psi, dtype=np.complex128)
        n_from_psi = _infer_n_modes_from_statevector(psi_arr)
        if n_from_psi != self.n_modes:
            raise FermionicPartialTraceError(
                f"plan has n_modes={self.n_modes}, but statevector has {n_from_psi} modes"
            )
        return self.sign.astype(np.complex128) * psi_arr[self.old_index]

    def reorder_density_matrix_to_keep_trace_order(self, rho: np.ndarray) -> ComplexArray:
        """
        Return the full density matrix expressed in mode order [keep..., trace...].
        Mostly useful for debugging and validation.
        """
        rho_arr = np.asarray(rho, dtype=np.complex128)
        n_from_rho = _infer_n_modes_from_density_matrix(rho_arr)
        if n_from_rho != self.n_modes:
            raise FermionicPartialTraceError(
                f"plan has n_modes={self.n_modes}, but density matrix has {n_from_rho} modes"
            )
        s = self.sign.astype(np.complex128)
        return (s[:, None] * s[None, :]) * rho_arr[np.ix_(self.old_index, self.old_index)]


def fermionic_partial_trace_statevector(
    psi: np.ndarray,
    keep: Sequence[int] | None = None,
    *,
    trace_out: Sequence[int] | None = None,
    n_modes: int | None = None,
    basis_order: BasisOrder = "little",
) -> ComplexArray:
    """
    Fermionically reduce a pure statevector to the requested modes.

    Parameters
    ----------
    psi:
        Full statevector in occupation/Jordan-Wigner basis.
    keep:
        Physical modes to keep, in the desired output order.
    trace_out:
        Alternative to `keep`: physical modes to trace out.
    n_modes:
        Optional number of modes. Inferred from len(psi) when omitted.
    basis_order:
        "little" for Qiskit-style integer indexing; "big" for textbook bit strings.
    """
    psi_arr = np.asarray(psi, dtype=np.complex128)
    inferred = _infer_n_modes_from_statevector(psi_arr)
    if n_modes is None:
        n_modes = inferred
    elif int(n_modes) != inferred:
        raise FermionicPartialTraceError(
            f"n_modes={n_modes} does not match statevector length {psi_arr.shape[0]}"
        )
    plan = FermionicPartialTracePlan(
        int(n_modes), keep=keep, trace_out=trace_out, basis_order=basis_order
    )
    return plan.trace_statevector(psi_arr)


def fermionic_partial_trace_density_matrix(
    rho: np.ndarray,
    keep: Sequence[int] | None = None,
    *,
    trace_out: Sequence[int] | None = None,
    n_modes: int | None = None,
    basis_order: BasisOrder = "little",
) -> ComplexArray:
    """
    Fermionically reduce a density matrix to the requested modes.

    Parameters
    ----------
    rho:
        Full density matrix in occupation/Jordan-Wigner basis.
    keep:
        Physical modes to keep, in the desired output order.
    trace_out:
        Alternative to `keep`: physical modes to trace out.
    n_modes:
        Optional number of modes. Inferred from rho.shape when omitted.
    basis_order:
        "little" for Qiskit-style integer indexing; "big" for textbook bit strings.
    """
    rho_arr = np.asarray(rho, dtype=np.complex128)
    inferred = _infer_n_modes_from_density_matrix(rho_arr)
    if n_modes is None:
        n_modes = inferred
    elif int(n_modes) != inferred:
        raise FermionicPartialTraceError(
            f"n_modes={n_modes} does not match density matrix shape {rho_arr.shape}"
        )
    plan = FermionicPartialTracePlan(
        int(n_modes), keep=keep, trace_out=trace_out, basis_order=basis_order
    )
    return plan.trace_density_matrix(rho_arr)


def fermionic_reduced_density_matrix(
    obj: np.ndarray,
    keep: Sequence[int] | None = None,
    *,
    trace_out: Sequence[int] | None = None,
    n_modes: int | None = None,
    basis_order: BasisOrder = "little",
) -> ComplexArray:
    """
    Convenience wrapper accepting either a statevector or density matrix.
    """
    arr = np.asarray(obj)
    if arr.ndim == 1:
        return fermionic_partial_trace_statevector(
            arr, keep=keep, trace_out=trace_out, n_modes=n_modes, basis_order=basis_order
        )
    if arr.ndim == 2:
        return fermionic_partial_trace_density_matrix(
            arr, keep=keep, trace_out=trace_out, n_modes=n_modes, basis_order=basis_order
        )
    raise FermionicPartialTraceError(
        f"expected statevector or density matrix, got array with shape {arr.shape}"
    )


def von_neumann_entropy(
    rho: np.ndarray,
    *,
    base: float = 2.0,
    tol: float = 1e-12,
    hermitize: bool = True,
    renormalize: bool = False,
) -> float:
    """
    Von Neumann entropy of a finite density matrix.

    Small negative eigenvalues from roundoff are clipped. Set renormalize=True
    only if you intentionally want to divide eigenvalues by their trace.
    """
    mat = np.asarray(rho, dtype=np.complex128)
    if mat.ndim != 2 or mat.shape[0] != mat.shape[1]:
        raise FermionicPartialTraceError(f"rho must be square, got {mat.shape}")
    if hermitize:
        mat = 0.5 * (mat + mat.conjugate().T)
    evals = np.linalg.eigvalsh(mat).real
    evals[np.abs(evals) < tol] = 0.0
    evals = np.clip(evals, 0.0, None)
    if renormalize:
        tr = float(evals.sum())
        if tr <= 0.0:
            return 0.0
        evals = evals / tr
    nz = evals[evals > tol]
    if nz.size == 0:
        return 0.0
    return float(-np.sum(nz * np.log(nz)) / log(base))


def fermionic_tmi_from_reduced_3mode_density(
    rho_abc: np.ndarray,
    *,
    basis_order: BasisOrder = "little",
    entropy_base: float = 2.0,
) -> float:
    """
    Tripartite mutual information I3(A:B:C) of a correctly fermionically
    reduced 3-mode density matrix.

    The input modes are interpreted locally as A=0, B=1, C=2 in the current
    8x8 matrix basis. If rho_abc was produced by keeping physical modes
    [i,j,k], then A=i, B=j, C=k in that order.
    """
    rho = np.asarray(rho_abc, dtype=np.complex128)
    if rho.shape != (8, 8):
        raise FermionicPartialTraceError(
            f"rho_abc must be an 8x8 three-mode density matrix, got {rho.shape}"
        )

    S_A = von_neumann_entropy(
        fermionic_partial_trace_density_matrix(rho, keep=[0], n_modes=3, basis_order=basis_order),
        base=entropy_base,
    )
    S_B = von_neumann_entropy(
        fermionic_partial_trace_density_matrix(rho, keep=[1], n_modes=3, basis_order=basis_order),
        base=entropy_base,
    )
    S_C = von_neumann_entropy(
        fermionic_partial_trace_density_matrix(rho, keep=[2], n_modes=3, basis_order=basis_order),
        base=entropy_base,
    )

    S_AB = von_neumann_entropy(
        fermionic_partial_trace_density_matrix(rho, keep=[0, 1], n_modes=3, basis_order=basis_order),
        base=entropy_base,
    )
    S_AC = von_neumann_entropy(
        fermionic_partial_trace_density_matrix(rho, keep=[0, 2], n_modes=3, basis_order=basis_order),
        base=entropy_base,
    )
    S_BC = von_neumann_entropy(
        fermionic_partial_trace_density_matrix(rho, keep=[1, 2], n_modes=3, basis_order=basis_order),
        base=entropy_base,
    )

    S_ABC = von_neumann_entropy(rho, base=entropy_base)

    return S_A + S_B + S_C - S_AB - S_AC - S_BC + S_ABC


def fermionic_tmi_from_statevector(
    psi: np.ndarray,
    modes: Sequence[int],
    *,
    n_modes: int | None = None,
    basis_order: BasisOrder = "little",
    entropy_base: float = 2.0,
) -> float:
    """
    Tripartite mutual information of three physical fermionic modes from a full
    pure statevector.
    """
    if len(tuple(modes)) != 3:
        raise FermionicPartialTraceError("modes must contain exactly three modes")
    rho_abc = fermionic_partial_trace_statevector(
        psi, keep=tuple(modes), n_modes=n_modes, basis_order=basis_order
    )
    return fermionic_tmi_from_reduced_3mode_density(
        rho_abc, basis_order=basis_order, entropy_base=entropy_base
    )


def fermionic_tmi_from_density_matrix(
    rho: np.ndarray,
    modes: Sequence[int],
    *,
    n_modes: int | None = None,
    basis_order: BasisOrder = "little",
    entropy_base: float = 2.0,
) -> float:
    """
    Tripartite mutual information of three physical fermionic modes from a full
    density matrix.
    """
    if len(tuple(modes)) != 3:
        raise FermionicPartialTraceError("modes must contain exactly three modes")
    rho_abc = fermionic_partial_trace_density_matrix(
        rho, keep=tuple(modes), n_modes=n_modes, basis_order=basis_order
    )
    return fermionic_tmi_from_reduced_3mode_density(
        rho_abc, basis_order=basis_order, entropy_base=entropy_base
    )


def ring_3mode_subsystems(n_modes: int, *, closed: bool = True) -> list[tuple[int, int, int]]:
    """
    Return distance-1 three-mode neighborhoods.

    closed=True:
        [(0,1,2), (1,2,3), ..., (N-1,0,1)]
    closed=False:
        [(0,1,2), ..., (N-3,N-2,N-1)]
    """
    n = int(n_modes)
    if n < 3:
        raise FermionicPartialTraceError("need at least three modes")
    if closed:
        return [(i, (i + 1) % n, (i + 2) % n) for i in range(n)]
    return [(i, i + 1, i + 2) for i in range(n - 2)]


def make_ring_3mode_plans(
    n_modes: int,
    *,
    closed: bool = True,
    basis_order: BasisOrder = "little",
) -> list[FermionicPartialTracePlan]:
    """Precompute plans for all distance-1 three-mode neighborhoods."""
    return [
        FermionicPartialTracePlan(n_modes, keep=subsys, basis_order=basis_order)
        for subsys in ring_3mode_subsystems(n_modes, closed=closed)
    ]


def tmi_block_subsystems(n_modes: int) -> list[tuple[int, ...]]:
    """
    Return the four mode groups stored by the C++/Python TMI .bin format.

    For N modes, with block=N/4, the stored order is:
        AB, AC, BC, D
    where
        A=[0, ..., block-1]
        B=[block, ..., 2*block-1]
        C=[2*block, ..., 3*block-1]
        D=[3*block, ..., 4*block-1]
    """
    n = int(n_modes)
    if n < 4 or (n % 4) != 0:
        raise FermionicPartialTraceError(
            "TMI block subsystems require n_modes >= 4 and divisible by 4"
        )

    block = n // 4
    A = tuple(range(0, block))
    B = tuple(range(block, 2 * block))
    C = tuple(range(2 * block, 3 * block))
    D = tuple(range(3 * block, 4 * block))

    return [A + B, A + C, B + C, D]


def make_tmi_block_plans(
    n_modes: int,
    *,
    basis_order: BasisOrder = "little",
) -> list[FermionicPartialTracePlan]:
    """Precompute fermionic partial-trace plans for TMI terms AB, AC, BC, D."""
    return [
        FermionicPartialTracePlan(n_modes, keep=subsys, basis_order=basis_order)
        for subsys in tmi_block_subsystems(n_modes)
    ]


# Short aliases for interactive use.
fpt_statevector = fermionic_partial_trace_statevector
fpt_density_matrix = fermionic_partial_trace_density_matrix
fpt = fermionic_reduced_density_matrix


def _ordinary_suffix_trace_density_matrix(
    rho: np.ndarray,
    keep_dim: int,
    trace_dim: int,
    basis_order: BasisOrder,
) -> np.ndarray:
    out = np.zeros((keep_dim, keep_dim), dtype=np.complex128)
    for tr in range(trace_dim):
        idx = _suffix_block_indices(keep_dim, trace_dim, tr, basis_order)
        out += rho[np.ix_(idx, idx)]
    return out


def _run_self_tests() -> None:
    rng = np.random.default_rng(12345)

    # Statevector path equals density-matrix path for pure states.
    for basis_order in ("little", "big"):
        n = 4
        dim = 1 << n
        psi = rng.normal(size=dim) + 1j * rng.normal(size=dim)
        psi = psi.astype(np.complex128)
        psi /= np.linalg.norm(psi)
        rho = np.outer(psi, psi.conjugate())
        for keep in ([0, 2], [2, 0], [3, 0, 1], [1]):
            a = fermionic_partial_trace_statevector(psi, keep=keep, basis_order=basis_order)
            b = fermionic_partial_trace_density_matrix(rho, keep=keep, basis_order=basis_order)
            if not np.allclose(a, b, atol=1e-12):
                raise AssertionError((basis_order, keep, np.max(np.abs(a - b))))
            if not np.allclose(np.trace(a), 1.0, atol=1e-12):
                raise AssertionError((basis_order, keep, np.trace(a)))
            if not np.allclose(a, a.conjugate().T, atol=1e-12):
                raise AssertionError((basis_order, keep, "non-Hermitian"))

    # Keeping a canonical prefix requires no fermionic reordering; it is the
    # ordinary suffix trace.
    for basis_order in ("little", "big"):
        n = 4
        dim = 1 << n
        x = rng.normal(size=(dim, dim)) + 1j * rng.normal(size=(dim, dim))
        rho = x @ x.conjugate().T
        rho /= np.trace(rho)
        keep = [0, 1]
        got = fermionic_partial_trace_density_matrix(rho, keep=keep, basis_order=basis_order)
        want = _ordinary_suffix_trace_density_matrix(
            rho, keep_dim=4, trace_dim=4, basis_order=basis_order
        )
        if not np.allclose(got, want, atol=1e-12):
            raise AssertionError((basis_order, "prefix trace mismatch", np.max(np.abs(got - want))))

    # TMI of a product pure state should be zero.
    psi0 = np.zeros(8, dtype=np.complex128)
    psi0[0] = 1.0
    if abs(fermionic_tmi_from_statevector(psi0, modes=[0, 1, 2], n_modes=3)) > 1e-12:
        raise AssertionError("product-state TMI should be zero")

    print("fermionic_partial_trace.py self-tests passed")


if __name__ == "__main__":
    _run_self_tests()
